---
title: "About Me"
---

I am a qualified running coach, but my real education comes from experience. 

Since 2014, I have spent years researching and experimenting to find out what truly works. I aim to train in a way that **prioritises health to achieve performance**, whereas many traditional plans chase performance at the expense of health.

I have researched running, nutrition, mental training, strength training, and went down every rabbit hole I can find. I remain open-minded, largely due to my own transformative experience with diet and lifestyle.

## My Qualifications
I hold the official coaching certifications from **England Athletics**:

* **LiRF** (Leader in Running Fitness)
* **CiRF** (Coach in Running Fitness)

---

## My Journey
If I can do it, anyone can.

My journey into running started from a place of struggle. I used to weigh **20 stone** and relied on a **walking stick** due to a crippling foot condition (Ledderhose disease).

I reversed my health through the very methods I now teach—nutrition, barefoot movement, and patience.

[Read more about my journey with Plantar Fibroma](https://ledderhose.blogspot.com/2011/11/plantar-fibroma-real-pain-in-foot.html)