---
title: "My Library"
---

Below is a list of books I own or have read as part of my aim to become the best coach I can be. I intend to write reviews and key points on all these books.

The books highlighted with a ⭐ are my **top recommendations** in each section.

## Primal Training
* ⭐ **[Primal Endurance](https://unrunningcoach.blogspot.com/2023/12/primal-endurance.html)** by Mark Sisson and Brad Kearns
* **Primal Blueprint** by Mark Sisson
* **Go Wild** by John J. Ratey & Richard Manning

## Typical Running Training
* **[Run Elite](https://unrunningcoach.blogspot.com/2024/01/runelite.html)** by Andrew Snow
* **Personal Best Running** by Mark Coogan & Scott Douglas
* **High Performance Middle-Distance Running** by David Sunderland
* **Running: From Middle Distance to Marathon** by Alex Reid & Garry Palmer
* **[Advanced Marathoning](https://unrunningcoach.blogspot.com/2024/02/advancedmarathon.html)** by Peter Pfitzinger & Scott Douglas
* **Hansons Marathon Method** by Humphrey & Hanson
* **Born to Run 2** by Christopher McDougall
* **[Athletics](https://unrunningcoach.blogspot.com/2024/02/athletics.html)** by Percy Curetty
* ⭐ **[Run for your life](https://unrunningcoach.blogspot.com/2024/01/runlife.html)** by Mark Cucuzzella M.D.

## Diet and Nutrition
* **[The Great Cholesterol Con](https://unrunningcoach.blogspot.com/2024/01/cholesterolcon.html)** by Dr. Malcolm Kendrick
* ⭐ **[The Carnivore Code](https://unrunningcoach.blogspot.com/2023/12/unleashing-human-within-carnivore-code.html)** by Paul Saladino
* **The Carnivore Diet** by Shawn Baker
* **The Art and Science of Low Carbohydrate Performance** by Volek & Phinney
* **Carnivore Cooking for Cool Dudes** by Brad Kearns
* **Sports Performance: Leaner, Fitter, Faster** by Grant Schofield & Caryn Zinn
* **The Low-Carb Athlete** by Ben Greenfield
* **The Real Meal Revolution** by Prof. Tim Noakes
* **The Case for Keto** by Gary Taubes

## Running Interest
* **[Amazing Racers](https://unrunningcoach.blogspot.com/2024/01/amazingracers.html)** by Marc Bloom
* **1:59: The Sub-Two-Hour Marathon** by Philip Maffetone & Bill Katovsky
* **Running in the Midpack** by Martin Yelling & Anji Andrews
* **Relentless** by Alistair Brownlee
* **Iron War** by Matt Fitzgerald
* **A Life Without Limits** by Chrissie Wellington
* **Endure** by Alex Hutchinson
* **The Sports Gene** by David Epstein
* **The Rise of the Ultra Runners** by Adharanand Finn
* **[Born to Run](https://unrunningcoach.blogspot.com/2024/01/borntorun.html)** by Christopher McDougall
* ⭐ **[Running with the Kenyans](https://unrunningcoach.blogspot.com/2024/02/running-with-kenyans.html)** by Adharanand Finn
* **My Life on the Run** by Bart Yasso
* **Running My Life** by Seb Coe
* **[The Greatest: Haile Gebrselassie](https://unrunningcoach.blogspot.com/2024/01/Gebrselassie.html)** by Jim Denison
* **[Run Britain](https://unrunningcoach.blogspot.com/2024/01/run-britain-by-nick-butter-travelling.html)** by Nick Butter
* ⭐ **[Out of Thin Air](https://unrunningcoach.blogspot.com/2024/01/OutOfThinAir.html)** by Michael Crawley

## Sleep and Recovery
* **Why We Sleep** by Matthew Walker
* **WIN: Achieve Peak Athletic Performance** by Tristin Kennedy

## Mental Training
* **Grit** by Angela Duckworth
* ⭐ **[Beyond Grit](https://unrunningcoach.blogspot.com/2024/01/BeyondGrit%20.html)** by Cindra Kamphoff
* **The Comeback Quotient** by Matt Fitzgerald
* **[Presence](https://unrunningcoach.blogspot.com/2024/01/presence.html)** by Amy Cuddy
* ⭐ **[The Confident Mind](https://unrunningcoach.blogspot.com/2023/12/a-confident-mind.html)** by Dr Nate Zinsser
* **Zero Negativity** by Ant Middleton
* **Applied Sport Psychology** by Jean Williams
* **The Art of Resilience** by Ross Edgley
* **Mindset** by Carol Dweck
* **[The Expectation Effect](https://unrunningcoach.blogspot.com/2024/01/expectationeffect.html)** by David Robson

## Science and Stuff
* **[Exercised](https://unrunningcoach.blogspot.com/2024/02/exercised.html)** by Daniel Lieberman
* **Peak** by Dr. Marc Bubbs
* **Peak Performance** by Brad Stulberg & Steve Magness
* **Lore of Running** by Tim Noakes
* **Lies My Doctor Told Me** by Ken Berry

## Strength Training & Biomechanics
* **Strength Training for Speed** by James Wild
* **Built to Move** by Kelly & Juliet Starrett
* **The Lost Art of Running** by Shane Benzie & Tim Major
* **Programmed to Run** by Thomas Miller
* **Running Form** by Owen Anderson
* **Barefoot Running Step by Step** by Ken Bob Saxton